### ISSUE TITLE
Исключение зависимости Yggdrasil

### ISSUE THREAD

**Issue by nxshock** [Mimir-IM/MimirForAndroid#2]
Предлагаю исключить зависимость держать постоянно включенным Yggdrasil и тем самым занимать слот VPN путём включения в Mirmir Yggdrasil-роутера, как это сделано в YggMail.

**Comment by Revertron** [comment]
Этот мессенджер сделан исключительно для использования при работающей сети Yggdrasil.
Отклонено.

**Comment by anotherdoesnm** [comment]
Удивительный факт: эту фичу похоже реализовали

**Comment by Revertron** [comment]
Просто нода Yggdrasil теперь внутри приложения. И используется реализация yggquic.

**Comment by anotherdoesnm** [comment]
так OP это и просил, нет?

**Comment by Revertron** [comment]
Да
