### ISSUE TITLE
Create an extensible protocol

### ISSUE THREAD

**Issue by Revertron** [Mimir-IM/MimirForAndroid#23]
Protocol should be extensible in a sense that any unknown to old versions of app properties of any message should be just discarded, but known should be read and used.

**Comment by Revertron** [comment]
Implemented a monster.
The main problem, that I was trying to solve - new versions of client apps will have new fields (meta-data) of messages. But old clients have very constraint field number, that they read one after another, and introducing new field is breaking communication between old and new clients.

There are some extendable protocols, like XML, for example. It works perfectly in XMPP - you can add new attributes for any stanzas (tags), you can add new stanzas, that will be just discarded by old clients without any problems.
But the problem arizes when you need to send binary data. You either encode it in Base64 (increasing it's size by 1.5), or invent some workaround servers, HTTP-servers and so on.

But we have one extendable protocol, that we use every day - HTTP. You can add many new and unknown headers from server or client side, and the communication works perfectly. And you don't need to encode binary data (unless yo really want).

Therefore, I've decided to make it pretty much the same, but slightly different. I encode headers/meta-data in JSON. We send these parts:
1. Size of JSON part (4 bytes).
2. JSON with all the metadata we need.
3. If the `payloadSize` in JSON is present and is greater than zero we read bytes into a byte array. (The message text, image, etc.)

**Comment by cleverfox** [comment]
Have a look to msgpack It schemaless like JSON, but it binary and can easily carry binary data inside with very little overhead.

**Comment by Revertron** [comment]
It would need to add a dependency.
